version: 2

builds:
  - goos:
    - linux
    - darwin
    - windows

brews:
  - repository:
      owner: mrtimp
      name: homebrew-formulas
    directory: Formula
    homepage: "https://github.com/mrtimp/terra-profile"
    description: "Automatically set the AWS_PROFILE for Terraform/Terragrunt based on configuration"
    commit_author:
      name: mrtimp
      email: timp@unfuddle.nz
